services:
  backend:
    build:
      context: ./backend
    container_name: sac_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DB_HOST=aws-1-us-east-2.pooler.supabase.com
      - DB_PORT=6543
      - DB_NAME=postgres
      - DB_USER=postgres.rsmxmirttcvvxmexunpl
      - DB_PASSWORD=z1QlZIHiYHrrVcve
    entrypoint: ["/app/entrypoint.sh"]
