# Usa la imagen oficial de Nginx
FROM nginx:alpine

# Copia tu archivo de configuración en el lugar adecuado
COPY default.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80 (donde escucha Nginx)
EXPOSE 80
