# Generated by Django 5.2.5 on 2025-09-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'escuelas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=120, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_recibido', models.DateField()),
            ],
            options={
                'db_table': 'inventario_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioTrazabilidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('accion', models.TextField()),
                ('detalle', models.TextField(blank=True, null=True)),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario_trazabilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=120)),
                ('salon', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('rol', models.TextField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
